### ISSUE TITLE
Crear Recetas fit y Contar Macros

### ISSUE THREAD

**Issue by raf181** [NuriZen/nurizen.github.io#14]
Recetas para nutrition

**Comment by BCAA-GitHub** [comment]
RECETAS DEFINICIÓN
1. Ensalada de verduras y pollo a la parrilla

Ingredientes:

4 oz (113 g) de pechuga de pollo asada
Ensalada mixta de verduras
tomates cherry
Rebanadas de pepino
Aderezo de vinagreta balsámica.
Preparación:

Asa el pollo hasta que esté completamente cocido y córtalo en rodajas.
Prepare la ensalada con una mezcla de verduras, tomates cherry y pepino.
Cubra con pollo asado y rocíe con vinagreta balsámica.
Calorías:

Aproximadamente 450 calorías por porción.
2. Sopa De Lentejas Y Verduras

Ingredientes:

1 taza de lentejas cocidas
Verduras variadas (zanahorias, apio, cebollas, etc.)
Caldo de vegetales
Hierbas y especias para condimentar.
Preparación:

Saltear las verduras en una olla.
Agrega el caldo de verduras y las lentejas cocidas.
Sazone con hierbas y especias.
Cocine a fuego lento hasta que las verduras estén tiernas.
Calorías:

Aproximadamente 400 calorías por porción.
3. Fideos de calabacín y camarones a la parrilla

Ingredientes:

4 onzas (113 g) de camarones asados
Fideos de calabacín (zoodles)
Ajo, jugo de limón y perejil para darle sabor.
Preparación:

Asa los camarones hasta que estén completamente cocidos.
Saltee los fideos de calabacín con ajo en una sartén.
Cubra los zoodles con camarones asados ​​y una pizca de jugo de limón y perejil.
Calorías:

Aproximadamente 500 calorías por porción.
4. Pimientos morrones rellenos de quinua y frijoles negros

Ingredientes:

Pimientos
1/2 taza de quinua cocida
1/2 taza de frijoles negros
Salsa de tomate
Preparación:

Corta la parte superior de los pimientos morrones y quita las semillas.
Mezcle la quinua cocida y los frijoles negros, luego rellene los pimientos.
Coloque los pimientos rellenos en una fuente para horno, cubra con salsa de tomate y hornee hasta que los pimientos estén tiernos.
Calorías:

Aproximadamente 450 calorías por porción.
5. Salmón Al Horno Con Espárragos

Ingredientes:

4 onzas (113 g) de filete de salmón
Lanzas de espárragos frescos
Rodajas de limón, ajo y hierbas para condimentar.
Preparación:

Sazone el salmón con limón, ajo y hierbas.
Coloque el salmón y los espárragos en una bandeja para hornear.
Hornee hasta que el salmón se desmenuce fácilmente.
Calorías:

Aproximadamente 500 calorías por porción.
6. Tortilla de espinacas y champiñones

Ingredientes:

2 huevos grandes
Espinaca
Champiñones rebanados
Queso bajo en grasa (opcional)
Preparación:

Batir los huevos y verter en una sartén antiadherente caliente.
Agrega las espinacas y los champiñones.
Dobla la tortilla y cocina hasta que cuaje.
Agregue queso si lo desea.
Calorías:

Aproximadamente 450 calorías por porción.
7. Salteado de pavo y verduras

Ingredientes:

4 oz (113 g) de pavo molido magro
Verduras salteadas variadas
Salsa para saltear baja en sodio
1/2 taza de arroz integral cocido
Preparación:

Cocine el pavo molido en una sartén hasta que se dore.
Sofreír las verduras y añadir el pavo cocido.
Agregue la salsa para saltear y cocine hasta que esté completamente caliente.
Sirva sobre arroz integral.
Calorías:

Aproximadamente 500 calorías por porción.
8. Parfait de yogur griego y frutos rojos

Ingredientes:

1 taza de yogur griego
Bayas mixtas (por ejemplo, fresas, arándanos)
2 cucharadas de granola (opcional)
Preparación:

Coloque capas de yogur griego, frutos rojos y granola en un vaso o tazón.
Calorías:

Aproximadamente 450 calorías por porción.
9. Salteado de tofu y verduras

Ingredientes:

4 oz (113 g) de tofu extra firme, en cubos
Verduras salteadas variadas
Salsa para saltear baja en sodio
1/2 taza de quinua cocida
Preparación:

Presiona y corta el tofu en cubos.
Sofreír el tofu y las verduras en un poco de aceite hasta que se dore.
Agregue la salsa para saltear y cocine hasta que esté completamente caliente.
Sirva sobre quinua cocida.
Calorías:

Aproximadamente 550 calorías por porción.

RECETAS VOLUMEN
1. Tazón de quinua y pollo rico en calorías

Ingredientes:

340 g de pechuga de pollo deshuesada y sin piel
120 g de quinua cocida
200 g de brócoli al vapor
30 g de almendras laminadas
Aceite de oliva, especias y condimentos para marinar y cocinar el pollo.
Preparación:

Marina la pechuga de pollo con aceite de oliva, especias y condimentos de tu elección.
Ase o cocine el pollo hasta que esté completamente cocido.
Cocine la quinua según las instrucciones del paquete.
Cocine el brócoli al vapor hasta que esté tierno.
Reúna todos los ingredientes en un bol.
Macronutrientes:

Proteína: 80g
Carbohidratos: 90g
Grasa: 40g
Calorías:

Aproximadamente 1040 calorías por porción.
2. Tazón de burrito de batata y frijoles negros

Ingredientes:

200 g de arroz integral cocido
200 g de frijoles negros
200 g de batatas asadas
50 g de aguacate cortado en cubitos
Salsa, jugo de lima y especias para darle sabor.
Preparación:

Cocine el arroz integral según las instrucciones del paquete.
Ase las batatas hasta que estén tiernas.
Frijoles negros calientes.
Reúna todos los ingredientes en un bol.
Macronutrientes:

Proteína: 30g
Carbohidratos: 140g
Grasa: 20g
Calorías:

Aproximadamente 980 calorías por porción.
3. Avena rica en calorías con mantequilla de nueces y bayas

Ingredientes:

200 g de avena
40 g de mantequilla de almendras o de maní
125 g de frutos rojos variados
20 g de miel
Preparación:

Cocine la avena con agua o leche según las instrucciones del paquete.
Cubra con mantequilla de nueces, bayas mixtas y miel.
Macronutrientes:

Proteína: 24g
Carbohidratos: 120g
Grasa: 36g
Calorías:

Aproximadamente 920 calorías por porción.
4. Sándwich de pavo y aguacate rico en calorías

Ingredientes:

4 rebanadas de pan integral
226 g de pechuga de pavo
115 g de aguacate, en rodajas
Lechuga, tomate y condimentos de tu elección.
Preparación:

Arma el sándwich con pavo, aguacate, lechuga, tomate y condimentos entre las rebanadas de pan.
Macronutrientes:

Proteína: 50g
Carbohidratos: 70g
Grasa: 30g
Calorías:

Aproximadamente 950 calorías por porción.
5. Ensalada De Salmón Y Quinua

Ingredientes:

340 g de salmón asado
200 g de quinua cocida
200 g de verduras mixtas
55 g de queso feta
Aderezo de vinagreta balsámica.
Preparación:

Asa el salmón hasta que esté completamente cocido.
Cocine la quinua según las instrucciones del paquete.
Prepare salmón, quinua, verduras mixtas y queso feta.
Rocíe con aderezo de vinagreta balsámica.
Macronutrientes:

Proteína: 80g
Carbohidratos: 70g
Grasa: 36g
Calorías:

Aproximadamente 1100 calorías por porción.
6. Batido de avena y plátano con nueces

Ingredientes:

4 plátanos maduros
200 g de avena
40 g de mantequilla de almendras
240 ml de leche (láctea o vegetal)
20 g de miel
Preparación:

Combine los plátanos, la avena, la mantequilla de almendras, la leche y la miel en una licuadora.
Mezclar hasta que esté suave.
Macronutrientes:

Proteína: 48g
Carbohidratos: 280g
Grasa: 60g
Calorías:

Aproximadamente 1420 calorías por porción.
7. Salteado de garbanzos y verduras rico en calorías

Ingredientes:

200 g de arroz integral cocido
200 g de garbanzos
Surtido de verduras salteadas (pimientos morrones, brócoli, guisantes, etc.)
Salsa salteada de su elección (baja en sodio)
Preparación:

Cocine el arroz integral según las instrucciones del paquete.
Sofreímos los garbanzos y las verduras en un poco de aceite.
Agregue la salsa para saltear y cocine hasta que esté completamente caliente.
Sirva sobre arroz integral.
Macronutrientes:

Proteína: 30g
Carbohidratos: 140g
Grasa: 10g
Calorías:

Aproximadamente 940 calorías por porción.
8. Parfait de yogur griego rico en calorías

Ingredientes:

200 g de yogur griego
100 gramos de granola
100 g de frutos rojos variados
20 g de miel
Preparación:

Coloque capas de yogur griego, granola, frutos rojos y miel en un tazón o vaso.
Macronutrientes:

Proteína: 30g
Carbohidratos: 120g
Grasa: 24g
Calorías:

Aproximadamente 940 calorías por porción.
9. Salteado de verduras y tofu rico en calorías

Ingredientes:

340 g de tofu extra firme, en cubos
Verduras salteadas variadas
Salsa para saltear baja en sodio
200 g de quinua cocida
Preparación:

Presiona y corta el tofu en cubos.
Sofreír el tofu y las verduras en un poco de aceite hasta que se dore.
Agregue la salsa para saltear y cocine hasta que esté completamente caliente.
Sirva sobre quinua cocida.
Macronutrientes:

Proteína: 40g
Carbohidratos: 140g
Grasa: 10g
Calorías:

Aproximadamente 1040 calorías por porción.
