### ISSUE TITLE
Crear tutoriales para Avanzados

### ISSUE THREAD

**Issue by raf181** [NuriZen/nurizen.github.io#8]

**Comment by IvanGPR** [comment]
Pecho
Tríceps
Bíceps
Espalda
Pierna
Hombro
Glúteo
Abdomen

**Comment by IvanGPR** [comment]
Pecho


![Image](https://user-images.githubusercontent.com/114149269/198249183-09e5aef6-2927-4528-9809-f1312394e93d.png)

Tríceps

![Image](https://user-images.githubusercontent.com/114149269/198249431-a0ab2038-8ac7-428f-881f-53502c9d13cf.png)

Bíceps


![Image](https://user-images.githubusercontent.com/114149269/198249681-6a8478e8-3ddc-4f9a-9004-13185b96d4d8.png)

Espalda

**Comment by IvanGPR** [comment]
Espalda


![Image](https://user-images.githubusercontent.com/114149269/222410801-f3b86ac7-99e4-408f-8269-b92bd9cf4234.png)



![Image](https://user-images.githubusercontent.com/114149269/222410916-4402ed7d-6e86-45c0-8b90-03b11c6e6aa9.png)



![Image](https://user-images.githubusercontent.com/114149269/222410991-227dea7a-25ce-47ad-8bb1-de80e15250cf.png)

Abdomen


![Image](https://user-images.githubusercontent.com/114149269/222411371-32939fab-9c6c-4041-af75-e2195caf5d1b.png)


![Image](https://user-images.githubusercontent.com/114149269/222411496-32506332-7a4c-4e9a-950a-b7dac5719849.png)


Glúteo


![Image](https://user-images.githubusercontent.com/114149269/222411663-f92b463c-3976-4fbc-97d2-471ef5922d94.png)

Hombros



![Image](https://user-images.githubusercontent.com/114149269/222411831-567295cd-7fcd-49a4-81d0-25821cf52f79.png)



![Image](https://user-images.githubusercontent.com/114149269/222411919-0f4c8ea2-edd4-4519-8c69-ba039acb913b.png)



![Image](https://user-images.githubusercontent.com/114149269/222411993-41fe9b31-e7e7-4cb4-9707-e89bedace8aa.png)

Pierna


![Image](https://user-images.githubusercontent.com/114149269/222412099-4036b833-24fb-4e6c-b6e6-2389b24052ce.png)



![Image](https://user-images.githubusercontent.com/114149269/222412190-3fc59385-c869-4898-8d57-b8cebff9fa1f.png)



![Image](https://user-images.githubusercontent.com/114149269/222412291-cbfe66c9-2edc-48fc-a371-60be144846c4.png)



![Image](https://user-images.githubusercontent.com/114149269/222412380-9798c3ad-de03-4d1e-8f1d-23b165e2d9cb.png)

**Comment by IvanGPR** [comment]
**Pecho**

**Calentamiento**
3 series aumentando peso progresivamente de calentamiento

**Ejercicio 1**: Press de banca (5 series x 5 repeticiones)
.Descanso entre series: 3-5 minutos

**Ejercicio 2**: Press de banca inclinado con mancuernas (4 series x 8-10 repeticiones)
.Descanso entre series: 2-3 minutos
.Ajusta el banco a una inclinación de aproximadamente 30-45 grados.

**Ejercicio 4**: Pec deck (3 series x 10-12 repeticiones)
.Descanso entre series: 1-2 minutos

**Ejercicio 5**: Fondos en máquina (3 series x 8-10 repeticiones)
.Descanso entre series: 2 minutos
.Si no tienes acceso a una máquina de fondos, puedes hacer fondos en paralelas o fondos en máquina de asistencia.

**Comment by IvanGPR** [comment]
**Hombro**

**Calentamiento**
5 min movilidad de hombros
2 series aumentando peso progresivamente de press militar con barra

**Ejercicio 1**: Press militar con barra (5 series x 6-8 repeticiones)
.Descanso entre series: 2-3 minutos

**Ejercicio 2**: Press Arnold (3 series x 8-10 repeticiones)
.Descanso entre series: 2-3 minutos

**Ejercicio 3**: Elevaciones laterales con mancuernas (4 series x 10-12 repeticiones)
.Descanso entre series: 1-2 minutos
.Utiliza mancuernas ligeras y mantén un control estricto para evitar el impulso

**Ejercicio 5**: Face Pulls (3 series x 12-15 repeticiones)
Descanso entre series: 1-2 minutos

**Comment by IvanGPR** [comment]
**Espalda**

**Calentamiento**
3 series de Pull-Ups maximas
.Descanso entre series: 2-3 minutos
.Enfocándote en la técnica y el control

**Ejercicio 1**: Pulldown en polea alta con agarre ancho (4 series x 8-10 repeticiones)
.Descanso entre series: 2-3 minutos

**Ejercicio 2**: Remo con barra T (3 series x 8-10 repeticiones)
.Descanso entre series: 2-3 minutos
.Utiliza una barra T o una barra recta para este ejercicio

**Ejercicio 3**: Pulldown en polea alta con agarre estrecho (3 series x 10-12 repeticiones)
.Descanso entre series: 1-2 minutos

**Ejercicio 4**: Hiperextensiones (3 series x 12-15 repeticiones)
.Descanso entre series: 1-2 minutos
.Utiliza una máquina de hiperextensiones o un banco inclinado para trabajar los músculos erectores de la columna

**Comment by IvanGPR** [comment]
**Biceps**

**Calentamiento**
 4 series x 8-10 repeticiones de Curl con mancuernas martillo
.Descanso entre series: 1-2 minutos

**Ejercicio 1**: Curl en banco inclinado con mancuernas (3 series x 10-12 repeticiones)
.Descanso entre series: 1-2 minutos

**Ejercicio 2**: Curl 21s (3 series)
.Descanso entre series: 1-2 minutos
.Divide cada serie en tres partes:
.Realiza 7 repeticiones desde la posición completa hasta la mitad del recorrido
.Luego, realiza 7 repeticiones desde la mitad del recorrido hasta la parte superior
.Finaliza con 7 repeticiones completas desde la posición completa hasta la parte superior

**Ejercicio 3**: Curl de concentración (3 series x 10-12 repeticiones por brazo)
.Descanso entre series: 1-2 minutos
.Utiliza una mancuerna y un banco o una silla para apoyar el brazo

**Comment by IvanGPR** [comment]
**Triceps**

**Calentamiento**
4 series x repeticiones máximas de Fondos en paralelas 

**Ejercicio 1**: Extensiones de tríceps con mancuerna (4 series x 10-12 repeticiones):
.Descanso entre series: 2-3 minutos

**Ejercicio 2**: Extensiones de tríceps en polea alta por encima de la cabeza (3 series x 10-12 repeticiones)
.Descanso entre series: 1-2 minutos

**Ejercicio 3**: Extensiones de tríceps en polea alta con barra recta y agarre supino (4 series x 10-12 repeticiones)
.Descanso entre series: 1-2 minutos

**Ejercicio 3**: Press de tríceps en banco plano con barra (4 series x 8-10 repeticiones)
.Descanso entre series: 2-3 minutos

**Comment by IvanGPR** [comment]
Es importante recordar que este es un entrenamiento muy intenso y largo. Escucha a tu cuerpo, mantén una técnica adecuada y ajusta los pesos según sea necesario. También, asegúrate de mantener una buena hidratación y alimentación antes y después del entrenamiento para apoyar la recuperación. Siempre puedes consultar a uno de nuestros profesionales  del fitness o entrenadores personal antes de embarcarte en un programa de entrenamiento tan extenso y avanzado.

**Comment by IvanGPR** [comment]
**Pierna**

**Calentamiento**
 3 series x 20 repeticiones de Extensiones de cuádriceps
.Descanso entre series: 1-2 minutos

**Ejercicio 1**: Sentadillas (4 series x 6-8 repeticiones)

**Comment by raf181** [comment]
these all the needed data create pages and costumice theme, push to publick
